"""Create initial tables

Revision ID: 5f4d9d24dc94
Revises: 98eb1bbed238
Create Date: 2025-01-22 23:09:51.009869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4d9d24dc94'
down_revision: Union[str, None] = '98eb1bbed238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('water_logs')
    op.drop_table('workout_logs')
    op.drop_table('daily_progress')
    op.drop_table('food_logs')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('height', sa.FLOAT(), nullable=False),
    sa.Column('age', sa.INTEGER(), nullable=False),
    sa.Column('activity_level', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=100), nullable=False),
    sa.Column('calorie_goal', sa.INTEGER(), nullable=True),
    sa.Column('water_goal', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('food_logs',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('food_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('calories', sa.INTEGER(), nullable=False),
    sa.Column('protein', sa.FLOAT(), nullable=True),
    sa.Column('fats', sa.FLOAT(), nullable=True),
    sa.Column('carbs', sa.FLOAT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_progress',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('water_consumed', sa.INTEGER(), nullable=False),
    sa.Column('calories_consumed', sa.INTEGER(), nullable=False),
    sa.Column('calories_burned', sa.INTEGER(), nullable=False),
    sa.Column('steps', sa.INTEGER(), nullable=False),
    sa.Column('weight_measurement', sa.FLOAT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_logs',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('workout_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('calories_burned', sa.INTEGER(), nullable=False),
    sa.Column('intensity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('water_logs',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
